name: Dimensions
main: me.xxastaspastaxx.dimensions.Main
author: astaspasta
description: Allow players to easily build portals to another world
api-version: 1.13
version: 1.1.4
depend: [ProtocolLib]
softdepend: [WorldGuard]
commands:
   dimensions:
      description: Main command
      usage: /<command>
      aliases: [dim]